branch-defaults:
  master:
    environment: petclinic-dev
    group_suffix: null
deploy:
  artifact: target/petclinic.jar
global:
  application_name: petclinic
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
